name: Test

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    uses: pkgjs/action/.github/workflows/node-test.yaml@v0
    with:
      runs-on: ubuntu-latest, windows-latest
      upgrade-policy: all
